#!/bin/bash
DAEMON=/usr/bin/aria2c
CONF=/root/.config/aria2/aria2.conf	 


pid(){
PID=`pgrep -f "$DAEMON -D --conf-path=$CONF"`
}
getconf(){
	grep "$1" "$CONF"  |grep -v \# |cut -d '=' -f 2 |head -n 1
}

start(){
	pid
	if [ -z "$PID" ]; then
		echo "Starting aria2 rpc daemon"
		$DAEMON -D --conf-path=$CONF
	else
		echo "Aria2 rpc daemon is already running, PID=$PID"
	fi
	
}

stop(){
	pid
	if [ -z "$PID" ]; then
		echo "Aria2 rpc daemon is not running! Nothing to stop."
	else
		echo "Shutting down aria2 rpc daemon..."
		kill -15 $PID
	fi
}
restart(){
	stop
	while [ -n "$PID" ]
	do
		pid
		sleep 1
	done
	start
}

case "$1" in
	start)
		start
		;;

	stop)
		stop
		;;

	restart)
		restart
		;;

	cleanup)
		stop
		DIR=`getconf dir`
		SESSION=`getconf session`
	
		rm -f $DIR/*.torrent
		rm -f "$SESSION"
		touch "$SESSION"
		chmod 644 "$SESSION"
		files=`ls -1 $DIR/*.aria2`
		IFS=$'\n' 
		for aria2 in $files
		do
			file=`echo $aria2 |sed 's/\.aria2//'`
			rm -f $aria2
			rm -rf  $file
		done
		unset IFS
		sleep 1
		start
		;;
		
	update)
		oldlist=`getconf bt-tracker`
		list=`wget -qO- https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt|awk NF|sed ":a;N;s/\n/,/g;ta"`
		if [ -z "$oldlist" ]; then
			sed -i '$a bt-tracker='${list} $CONF
			echo add......
		else
				if [ "$oldlist" = "$list" ]; then
						echo No tracker update is needed
				else
						sed -i "s@bt-tracker.*@bt-tracker=$list@g" $CONF
						port=`getconf rpc-listen-port`
						passwd=`getconf rpc-secret`
						json={\"jsonrpc\":\"2.0\",\"method\":\"aria2.changeGlobalOption\",\"id\":\"ZGVvcnRo\",\"params\":[\"token:$passwd\",{\"bt-tracker\":\"$list\"}]}
						curl -X POST -d $json http://127.0.0.1:$port/jsonrpc  >/dev/null
						echo Update tracker......
						
						
				fi
		fi
		;;
	
	status)
		pid
		if [ -z "$PID" ]; then
			echo "Aria2 rpc daemon is not running!"
		else
			echo "Aria2 rpc daemon is running, PID=$PID"
		fi
		;;
	
	*)
		echo "Usage: /etc/init.d/aria2 {start|stop|restart|cleanup|update}"
		exit 1
		;;
esac
exit
